name: EJERCICIOS DE FLUJO CICD
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v4
      #- name: Analizar con Sonar
      #  uses: sonarsource/sonarqube-scan-action@master
      #  env:
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #    SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} 
            
      - name: Crear files
        run: |
          mkdir -p artefacto
          echo "Hello world!" > artefacto/hello.txt
      - name: Create ZIP
        run: zip -r artefacto.zip artefacto
        
      - uses: actions/upload-artifact@v4
        with:
          name: artefacto-${{github.actor}}
          path: artefacto.zip

  cd:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: artefacto-${{github.actor}}
          path: artefacto.zip
      - name: Unzip artefacto      
        run: | 
          ls
          unzip artefacto.zip -d artefacto
          ls -R
          cat artefacto/hello.txt
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          subject: Github Actions job result
          to: ivancamachoviveros@gmail.com, agccstarck@gmail.com, jorgesago@gmail.com
          from: Luke Skywalker
          
          
      
      
